// Generated by gencpp from file object_pose_estimation/ObjectHypothesisWithPose.msg
// DO NOT EDIT!


#ifndef OBJECT_POSE_ESTIMATION_MESSAGE_OBJECTHYPOTHESISWITHPOSE_H
#define OBJECT_POSE_ESTIMATION_MESSAGE_OBJECTHYPOTHESISWITHPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovariance.h>

namespace object_pose_estimation
{
template <class ContainerAllocator>
struct ObjectHypothesisWithPose_
{
  typedef ObjectHypothesisWithPose_<ContainerAllocator> Type;

  ObjectHypothesisWithPose_()
    : id(0)
    , score(0.0)
    , pose()  {
    }
  ObjectHypothesisWithPose_(const ContainerAllocator& _alloc)
    : id(0)
    , score(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef double _score_type;
  _score_type score;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectHypothesisWithPose_

typedef ::object_pose_estimation::ObjectHypothesisWithPose_<std::allocator<void> > ObjectHypothesisWithPose;

typedef boost::shared_ptr< ::object_pose_estimation::ObjectHypothesisWithPose > ObjectHypothesisWithPosePtr;
typedef boost::shared_ptr< ::object_pose_estimation::ObjectHypothesisWithPose const> ObjectHypothesisWithPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator1> & lhs, const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.score == rhs.score &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator1> & lhs, const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_pose_estimation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa1ab3bc7146f53921fa142d631d02db";
  }

  static const char* value(const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa1ab3bc7146f539ULL;
  static const uint64_t static_value2 = 0x21fa142d631d02dbULL;
};

template<class ContainerAllocator>
struct DataType< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_pose_estimation/ObjectHypothesisWithPose";
  }

  static const char* value(const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# An object hypothesis that contains position information.\n"
"\n"
"# The unique numeric ID of object detected. To get additional information about\n"
"#   this ID, such as its human-readable name, listeners should perform a lookup\n"
"#   in a metadata database. See vision_msgs/VisionInfo.msg for more detail.\n"
"int64 id\n"
"\n"
"# The probability or confidence value of the detected object. By convention,\n"
"#   this value should lie in the range [0-1].\n"
"float64 score\n"
"\n"
"# The 6D pose of the object hypothesis. This pose should be\n"
"#   defined as the pose of some fixed reference point on the object, such a\n"
"#   the geometric center of the bounding box or the center of mass of the\n"
"#   object.\n"
"# Note that this pose is not stamped; frame information can be defined by\n"
"#   parent messages.\n"
"# Also note that different classes predicted for the same input data may have\n"
"#   different predicted 6D poses.\n"
"geometry_msgs/PoseWithCovariance pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.score);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectHypothesisWithPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_pose_estimation::ObjectHypothesisWithPose_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_POSE_ESTIMATION_MESSAGE_OBJECTHYPOTHESISWITHPOSE_H
